//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snesclassicalert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>thinkgeek,http://www.thinkgeek.com/product/kmrn/?srp=5,IN STOCK</string>
  <string>BH,https://www.bhphotovideo.com/c/product/1347308-REG/nintendo_snes_super_nintendo_classic_edition.html,TYPE=""SUBMIT""&gt;ADD TO CART&lt;/BUTTON&gt;</string>
  <string>Amazon,https://www.amazon.com/Super-NES-Classic-nintendo/dp/B0721GGGS9/ref=sr_1_3?s=videogames&amp;ie=UTF8&amp;qid=1506823304&amp;sr=1-3&amp;keywords=super+nes+classic,&amp;quot;79.99&amp;quot</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Merchants {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Merchants"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sneshunter@gmail.com")]
        public string Email_From_Address {
            get {
                return ((string)(this["Email_From_Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7329916476@vtext.com")]
        public string Email_To_Address {
            get {
                return ((string)(this["Email_To_Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Email_Server {
            get {
                return ((string)(this["Email_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int Email_Port {
            get {
                return ((int)(this["Email_Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mbruno2084@gmail.com")]
        public string Email_Username {
            get {
                return ((string)(this["Email_Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HuFsApyr5j8AA4m7uyyHVdhPqmiJoCh2P8G2Pczo+7h3yDafLmiYa7X8H8touQ8iVxqr6sS4Eo0hA6jP5" +
            "C4OjX9zP51LRTcMpuy4xf7+tIR20+ZNLWipe3axCgww4F+DMvo0TjZxu+9JutVwIWRfpQ==")]
        public string Email_Password {
            get {
                return ((string)(this["Email_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SNES Hunter")]
        public string Email_To_Name {
            get {
                return ((string)(this["Email_To_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Email_Enable_SSL {
            get {
                return ((bool)(this["Email_Enable_SSL"]));
            }
        }
    }
}
